(require :asdf)
#-quicklisp
(let ((qlfile (merge-pathnames "quicklisp/setup.lisp" (user-homedir-pathname))))
  (when (probe-file qlfile) (load qlfile)))
(push (uiop:getcwd) asdf:*central-registry*)
#+quicklisp (ql:quickload :edi-dsl/tests :silent t)
#-quicklisp (asdf:load-system :edi-dsl/tests)
(let* ((suite (uiop:find-symbol* :all-tests :edi-dsl/tests))
       (results (fiveam:run suite)))
  (uiop:quit (if (fiveam:results-status results) 0 1)))
