(in-package #:x12-parser)

;;; A focused slice of 837D segments. Real 837D has dozens; these are the ones
;;; the fixture exercises end-to-end. Adding more is a one-line declaration each.

(define-segment "ISA" (:name :interchange-control-header)
  (1  :authorization-info-qualifier :required t)
  (2  :authorization-info)
  (3  :security-info-qualifier :required t)
  (4  :security-info)
  (5  :interchange-sender-qualifier :required t)
  (6  :interchange-sender-id :required t)
  (7  :interchange-receiver-qualifier :required t)
  (8  :interchange-receiver-id :required t)
  (9  :interchange-date :required t)
  (10 :interchange-time :required t)
  (11 :repetition-separator :required t)
  (12 :interchange-control-version :required t)
  (13 :interchange-control-number :required t)
  (14 :ack-requested :required t)
  (15 :usage-indicator :required t)
  (16 :component-element-separator :required t))

(define-segment "IEA" (:name :interchange-control-trailer)
  (1 :functional-group-count :required t)
  (2 :interchange-control-number :required t))

(define-segment "GS" (:name :functional-group-header)
  (1 :functional-id-code :required t)
  (2 :sender-code :required t)
  (3 :receiver-code :required t)
  (4 :date :required t)
  (5 :time :required t)
  (6 :group-control-number :required t)
  (7 :responsible-agency-code :required t)
  (8 :version-release-industry-id :required t))

(define-segment "GE" (:name :functional-group-trailer)
  (1 :transaction-count :required t)
  (2 :group-control-number :required t))

(define-segment "ST" (:name :transaction-set-header)
  (1 :transaction-set-id :required t)
  (2 :transaction-set-control-number :required t)
  (3 :implementation-convention-reference))

(define-segment "SE" (:name :transaction-set-trailer)
  (1 :segment-count :required t)
  (2 :transaction-set-control-number :required t))

(define-segment "BHT" (:name :beginning-of-hierarchical-transaction)
  (1 :hierarchical-structure-code :required t)
  (2 :transaction-set-purpose-code :required t)
  (3 :reference-id :required t)
  (4 :date :required t)
  (5 :time)
  (6 :claim-encounter-id))

(define-segment "NM1" (:name :individual-or-organizational-name)
  (1 :entity-identifier-code :required t)
  (2 :entity-type-qualifier :required t)
  (3 :name-last-or-organization-name :required t)
  (4 :name-first)
  (5 :name-middle)
  (8 :identification-code-qualifier)
  (9 :identification-code))

(define-segment "HL" (:name :hierarchical-level)
  (1 :hierarchical-id-number :required t)
  (3 :hierarchical-level-code :required t)
  (4 :hierarchical-child-code))

(define-segment "CLM" (:name :claim-information)
  (1 :claim-submitter-id :required t)
  (2 :total-claim-charge :required t)
  (5 :place-of-service-code))

(define-segment "SV3" (:name :dental-service)
  (1 :composite-medical-procedure-id :required t)
  (2 :line-item-charge :required t)
  (3 :oral-cavity-designation)
  (4 :prosthesis-crown-or-inlay-code)
  (5 :quantity))

(define-segment "DTP" (:name :date-time-period)
  (1 :date-time-qualifier :required t)
  (2 :date-time-format :required t)
  (3 :date-time-value :required t))
